### ISSUE TITLE
make tag colors configurable

### ISSUE THREAD

**Issue by tolry** [DavidBadura/doThings#31]
Certain tags could be colored differently, e.g. by default the "next" tag indicates importance and might therefore be displayed as red

example

``` yaml
tags:
    next: #ff0000
    _hold: #0000ff
```
