### ISSUE TITLE
quick filters

### ISSUE THREAD

**Issue by tolry** [DavidBadura/doThings#32]
It would be nice to have shortcuts for often used filters: e.g. next report + tag "quick" set. Those quick filters would be optional and might be defined in the main configuration.

``` yaml
quick_filters:
    quick: {report: next, filter: "+quick"}
    today: {report: next, filter: "due:today"}
    @work: {report: next, filter: "+@work"}
```

If used like this, the users wouldn't have to define lots of almost identical reports in there taskrc.

**Comment by DavidBadura** [comment]
that would be more of a feature for taskwarrior. to define a report based on an another report :wink: 

Until taskwarior has this feature, we can add this.
I think it should be optional to define a report.

``` yml
quick_filters:
    all: {sort: "due+"}
    today: {report: next, filter: "due:today"}
    @work: {filter: "+@work"}
```
